// src/renderer/src/components/SideBar/HeaderList.tsx
import { useEffect, useRef } from 'react'
import { HeaderTree, useHeaders } from './hooks/useHeaders'
const triangleDown = `<svg class='triangle-down' xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
<path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
</svg>`
export const HeaderList = () => {
  const headerListRef = useRef(null)
  const CLASS_NAME = 'header-list'
  const dfs = (tree: HeaderTree, container: HTMLElement | DocumentFragment) => {
    const id = tree.header.getAttribute('id')
    if (!tree.children.length) {
      const li = document.createElement('li')
      li.innerHTML = `<a href=${'#' + id}>${tree.header.innerText}</a>`
      li.setAttribute('style', `--i: ${Number(tree.tagName[1]) - 0.5}`)
      container.appendChild(li)
    } else {
      const ul = document.createElement('ul')
      ul.innerHTML = triangleDown + `<a href=${'#' + id}>${tree.header.innerText}</a>`
      ul.setAttribute('style', `--i: ${tree.tagName[1]}`)
      tree.children.forEach((child) => {
        dfs(child, ul)
      })
      ul.addEventListener('click', () => {
        ul.classList.toggle(CLASS_NAME)
      })
      container.appendChild(ul)
    }
    return container
  }
  const updateHeaders = (container: HTMLElement | null) => {
    if (!container) return
    container!.innerHTML = ''
    const headers =
      document.querySelector('.milkdown .editor')?.querySelectorAll('h1,h2,h3,h4,h5,h6') || []
    const Headers = Array.from(headers)
    const trees = useHeaders(Headers as HTMLElement[])
    trees.forEach((tree) => {
      const fragment = document.createDocumentFragment()
      const headerList = dfs(tree, fragment)
      container.appendChild(headerList)
    })
  }
  useEffect(() => {
    updateHeaders(headerListRef.current)
  }, [])
  return (
    <>
      <ul className={CLASS_NAME} ref={headerListRef}></ul>
      <button onClick={() => updateHeaders(headerListRef.current)}>update</button>
    </>
  )
}

// src/renderer/src/components/sidebar/components/header-list/components/header-list.vue
<template>
  <ul
    :class="{
      close: isClose
    }"
  >
    <li
      :style="{
        marginLeft: margin * 8 + 2 + 'px'
      }"
      @click.stop="handleClick"
    >
      <svg
        v-if="tree.children.length"
        class="triangle-down"
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        fill="currentColor"
        viewBox="0 0 16 16"
      >
        <path
          fillRule="evenodd"
          d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"
        />
      </svg>
      <span>
        {{ tree.header.innerText }}
      </span>
    </li>
    <template v-for="child in tree.children" :key="child.header">
      <header-list :tree="child" />
    </template>
  </ul>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { HeaderTree } from '../helper/getHeaderTree'
const props = defineProps<{
  tree: HeaderTree
}>()
const margin = Number(props.tree.tagName[1])
const isClose = ref(false)
const handleClick = () => {}
</script>

<style lang="scss">
// ul li {
//   display: flex;
//   align-items: center;
//   transition: all 0.3s;
//   height: auto;
//   cursor: pointer;
//   svg {
//     margin-right: 6px;
//     transform: rotateZ(-90deg);
//   }
// }
// ul.close {
//   height: 25px;
//   svg {
//     transform: rotateZ(0deg);
//   }
// }
</style>
