// src/renderer/src/components/Global/SearchFile.tsx
import { useEffect, useRef, useState } from 'react'

import { openFile } from '../../common/openFile'
type IFileList = {
  fileName: string
  filePath: string
}[]
interface ISearchFile {
  fileList: IFileList
  closeSearchFile: () => void
}
const mapFiles = (fileList: IFileList) => {
  const files = fileList.map((file, index) => {
    return (
      <li key={file.filePath} className={index === 0 ? 'active' : ''}>
        <span>{file.fileName}</span>
      </li>
    )
  })
  return files
}
export const SearchFile: React.FC<ISearchFile> = ({ fileList, closeSearchFile }) => {
  const [active, setActive] = useState(0)
  const iptRef = useRef<HTMLInputElement>(null)
  const filesContainer = useRef<HTMLUListElement>(null)

  const [files, setFiles] = useState(mapFiles(fileList))

  useEffect(() => {
    // 在active更新后执行，否则不会按照你的预定的去
    const lis = filesContainer.current?.children
    if (lis) {
      ;[...lis].forEach((li, _index) => {
        li.classList.remove('active')
      })
      const target = lis[active]
      target.classList.add('active')
      const io = new IntersectionObserver((entries) => {
        entries.forEach((entrie) => {
          //如果不可见,就需要向上滚动或者向下滚动
          if (entrie.intersectionRatio < 0.5) {
            // 显示十个，如果大于8，大于9都可以，表示向下滚动
            if (active > 8) target?.scrollIntoView(false)
            else target?.scrollIntoView(true)
          }
          // 不管是否可见，操作完就移除观察
          io.unobserve(target)
        })
      })
      io.observe(target)
    }
  }, [active])
  useEffect(() => {
    iptRef.current?.focus()
    const hanleSelect = (e: KeyboardEvent) => {
      const ARROW_DOWN = 'ArrowDown'
      const ARROW_UP = 'ArrowUp'
      if (e.code === ARROW_UP) {
        if (!files[active - 1]) {
          setActive(files.length - 1)
        } else {
          setActive(active - 1)
        }
      }
      if (e.code === ARROW_DOWN) {
        if (!files[active + 1]) {
          setActive(0)
        } else {
          setActive(active + 1)
        }
      }
      if (e.code === 'Enter') {
        const filePath = files[active]?.key as string
        filePath && openFile(filePath)
        closeSearchFile()
      }
    }
    document.addEventListener('keydown', hanleSelect)
    return () => document.removeEventListener('keydown', hanleSelect)
    // 因为处理函数里面有依赖到active，所以必须传递这个依赖进去
  }, [active, files])
  const updateFiles = () => {
    const searchStr = iptRef.current?.value || ''
    const newFileList = fileList.filter((file) => {
      if (file.fileName.toLocaleLowerCase().includes(searchStr.toLocaleLowerCase())) return true
      else return false
    })
    setFiles(mapFiles(newFileList))
    setActive(0)
  }
  return (
    <div className="search-file ">
      <div>
        <span>{active}</span>
        <input placeholder="" onChange={updateFiles} ref={iptRef} type="text" />
      </div>
      <ul ref={filesContainer}>{files}</ul>
    </div>
  )
}

// src/renderer/src/components/global/search-file.vue
<template>
  <div
    class="search-file"
  >
    <div>
      <span></span>
      <input v-model="search_content" type="text" />
    </div>
    <ul>
      <template v-for="(path, index) in paths" :key="path">
        <li
        @click="handleClick"
          :class="{
            'active': currentIndex === index
          }"
        >
          <span>{{ basename(path) }}</span>
        </li>
      </template>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useStore } from '../../store'
import { basename } from 'path-browserify'

const search_content = ref('')
const store = useStore()
const paths = computed(() =>
  store.totalPaths.filter((path) => basename(path).includes(search_content.value))
)
const currentIndex = ref(0)
const emits = defineEmits(['update-path','open-file'])
const handleClick = () => {emits('open-file')}
watch(currentIndex, () => {
  const target = document.querySelector('.active')
  if (!target) return
  const io = new IntersectionObserver((entries) => {
    entries.forEach((entrie) => {
      //如果不可见,就需要向上滚动或者向下滚动
      if (entrie.intersectionRatio < 0.5) {
        // 显示十个，如果大于8，大于9都可以，表示向下滚动
        if (currentIndex.value > 1) target?.scrollIntoView(false)
        else target?.scrollIntoView(true)
      }
      // 不管是否可见，操作完就移除观察
      io.unobserve(target)
    })
  })
  io.observe(target)
  emits('update-path',paths.value[currentIndex.value])
})
document.addEventListener('keydown', (e: KeyboardEvent) => {
  if (e.key === 'ArrowUp') {
    if (currentIndex.value === 0) currentIndex.value = paths.value.length-1
    else currentIndex.value -= 1
  }
  if(e.key ==='ArrowDown') {
    if(currentIndex.value===paths.value.length-1) currentIndex.value = 0
    else currentIndex.value +=1
  }
})

</script>

<style lang="scss" scoped>
.search-file {
  top: 30px;
  position: fixed;
  z-index: 9999;
  width: auto;
  left: 50%;
  transform: translateX(-50%);
  font-size: 12px;
  border-radius: 4px;
  div {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 25px;
    margin: 6px;
    input {
      height: 100%;
      width: 80%;
      border-width: 1.6px;
    }
  }
  ul {
    height: 300px;
    overflow: scroll;
  }
  li {
    height: 25px;
    display: flex;
    align-items: center;
    font-size: 15px;
    span {
      margin-left: 20px;
    }
    &:hover {
      cursor: pointer;
    }
  }
}
</style>
