// src/renderer/src/components/SideBar/components/SearchWordGlobal.tsx
import { ChangeEvent, useEffect, useRef, useState } from 'react'
import debounce from 'debounce'
import { SearchWords } from '../../../../../common/types'
import { openFile } from '../../../common/openFile'
const SearchItem: React.FC<{
  match: { fileName: string; path: string; matchs: string[] }
}> = ({ match }) => {
  const [autoHeight, setHeight] = useState(false)
  const openSelect = () => {
   match.path && openFile(match.path)
    // 在滚到指定位置
  }
  return (
    <ul
      style={{
        height: autoHeight ? 'auto' : '30px'
      }}
      onClick={() => setHeight(!autoHeight)}
    >
      <li className="fileName" onClick={openSelect}>
        <svg
          className={autoHeight ? '' : 'open'}
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          fill="currentColor"
          viewBox="0 0 16 16"
        >
          <path
            fillRule="evenodd"
            d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"
          />
        </svg>
        {match.fileName}
      </li>
      {match.matchs.map((paragraph, index) => {
        return <li key={index}>{paragraph}</li>
      })}
    </ul>
  )
}
export const SearchWordGlobal: React.FC<{
  show: boolean
}> = ({ show }) => {
  const [word, setWord] = useState('')
  const debouncedSetWord = debounce(setWord, 500)
  const [total,setTotal] = useState(0)
  const [matchs, setMatchs] = useState<SearchWords>()
  const iptChange = (e: ChangeEvent<HTMLInputElement>) => {
    debouncedSetWord(e.target.value)
  }
  const iptRef = useRef<HTMLInputElement>(null)
  useEffect(() => {
    window.api.searchDirWord(word).then((res) => {
      setMatchs(res)
      const total = res.reduce((preSum,file)=>{
        return file.matchs.length + preSum
      },0)
    setTotal(total)
    })
  }, [word])
  useEffect(()=>{
    iptRef.current?.focus()
    console.log('📕',iptRef.current)
  },[show])
  iptRef.current?.focus()

  return (
    <div
      className="swg"
      style={{
        display: show ? 'block' : 'none'
      }}
    >
      <div className='input'>
        <input type="text" onChange={iptChange} />
      </div>
      <div className="tip">在 {matchs?.length} 个文件中有 {total} 个结果</div>
      {matchs &&
        matchs.map((match) => {
          return <SearchItem key={match.path} match={match} />
        })}
    </div>
  )
}

// src/renderer/src/components/sidebar/components/search-word-global/index.vue
<template>
  <div class="search-word-global">
    <div className="input-container">
      <input type="text" v-model="keyWord" ref="iptRef" />
    </div>
    <div class="tip">在 {{ totalPaths }} 个文件中有 {{ totalMatchs }} 个结果</div>
    <div class="search-results">
      <template v-for="file in results" :key="file.path">
        <search-item :file="file" />
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import debouce from 'debounce'
import { SearchWords } from '../../../../../../common/types'
import { GET_SEARCH_RESULT } from '../../../../../../common/eventType'
import SearchItem from './search-item.vue'
const iptRef = ref<HTMLInputElement>()
const keyWord = ref('')
const results = ref<SearchWords[]>([
  {
    fileName: '未找到结果',
    path: '',
    matchs: [
      {
        line: 'not-found',
        index: 0
      }
    ]
  }
])
const totalMatchs = ref(0)
const totalPaths = ref(0)

watch(
  keyWord,
  debouce(() => {
    window.api.interProcess(GET_SEARCH_RESULT, keyWord.value).then((response) => {
      console.log('📕', response)
      results.value = response
    })
  }, 800)
)
onMounted(() => {
  iptRef.value?.focus()
  // 重复按键就聚焦
  document.addEventListener('keydown', (e) => {
    if (e.metaKey && e.key === 'f' && e.shiftKey) {
      iptRef.value?.focus()
    }
  })
})
</script>

<style lang="scss">
.search-word-global {
  position: absolute;
  z-index: 100;
  overflow: scroll;
  height: 100%;
  width: 100%;
  padding: 10px 0;
  top: 0;
  .input-container {
    margin: 10px 0;
    display: flex;
    justify-content: center;
    height: 25px;
    input {
      width: 80%;
      height: 100%;
    }
  }
  svg {
    transition: all 0.5s;
  }
  svg.open {
    transform: rotateZ(-90deg);
  }
  div.tip {
    margin: 8px;
  }
}
</style>
