// src/renderer/src/components/SideBar/components/DragLine.tsx
export const DragLine = () => {
  const dragLineMove = (e: React.MouseEvent) => {
    // clietX就是距离浏览器视口的位置
    const clientX = e.clientX
    const dragLine = document.querySelector('.drag-line') as HTMLElement
    document.onmousemove = (e) => {
      const newClientX = e.clientX
      const moveDistance = newClientX - clientX
      const nextPosition = clientX + moveDistance
      dragLine.style.left = nextPosition + 'px'
      return false
    }

    // 释放鼠标的时候解除事件绑定
    document.onmouseup = (e) => {
      const newPosition = e.clientX
      // 如果太宽了就返回原来的位置
      // 小于等于100是侧边栏的最少宽度
      if (newPosition <= 100 || newPosition > 600) {
        dragLine.style.left = clientX + 'px'
      } else {
        dragLine.style.left = newPosition + 'px'
        const sideBar = document.querySelector('.side-bar') as HTMLElement
        sideBar.style.width = newPosition + 'px'
      }

      document.onmousemove = null
      document.onmouseup = null
      return false
    }
  }
  return <div className="drag-line" onMouseDown={dragLineMove}></div>
}

// src/renderer/src/components/sidebar/components/drag-line/drag-line.vue
<template>
    <!-- 为了避免overflow显示异常，这里使用teleport传送 -->
  <Teleport to="body">
    <div
      class="drag-line"
      :style="{ marginLeft: width + moveDistance + 'px' }"
      @mousedown="handleMouseDown"
    ></div>
  </Teleport>
</template>

<script setup lang="ts">
import { ref } from 'vue'
defineProps<{ width: number }>()
const moveDistance = ref(0)
const emits = defineEmits(['drag-done'])
const handleMouseDown = (e: MouseEvent) => {
  // clietX就是距离浏览器视口的位置
  const clientX = e.clientX
  document.onmousemove = (e) => {
    const newClientX = e.clientX
    moveDistance.value = newClientX - clientX
    return false
  }
  // 释放鼠标的时候解除事件绑定
  document.onmouseup = (e) => {
    const newPosition = e.clientX
    emits('drag-done', newPosition)
    moveDistance.value = 0
    document.onmousemove = null
    document.onmouseup = null
    return false
  }
}
</script>

<style lang="scss">
.drag-line {
  width: 3px;
  position: absolute;
  height: 100%;
  top: 0;
  z-index: 99999;
  margin-left: 100px;
  background-color: rgb(172, 203, 228) !important;
  opacity: 0;
  &:hover {
    cursor: ew-resize;
    scale: 1.2;
    opacity: 100%;
  }
}
</style>
